// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/dashboard" | "/admin/dashboard/field-workers" | "/admin/dashboard/field-workers/[workerId]" | "/admin/dashboard/overview" | "/admin/dashboard/sites" | "/admin/dashboard/sites/[siteId]" | "/admin/dashboard/sites/[siteId]/projectors/[projectorId]" | "/dashboard" | "/form" | "/login" | "/user/profile" | "/user/services" | "/user/workflow"
type AppRouteHandlerRoutes = "/api/admin/field-workers" | "/api/admin/field-workers/[workerId]/work-history" | "/api/admin/field-workers/create" | "/api/admin/overview" | "/api/admin/projectors" | "/api/admin/services/schedule" | "/api/admin/sites" | "/api/admin/sites/[siteId]" | "/api/admin/tasks" | "/api/auth/[...all]" | "/api/blob/upload" | "/api/session" | "/api/user/profile" | "/api/user/services" | "/api/user/services/complete" | "/api/user/services/completed"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/dashboard": {}
  "/admin/dashboard/field-workers": {}
  "/admin/dashboard/field-workers/[workerId]": { "workerId": string; }
  "/admin/dashboard/overview": {}
  "/admin/dashboard/sites": {}
  "/admin/dashboard/sites/[siteId]": { "siteId": string; }
  "/admin/dashboard/sites/[siteId]/projectors/[projectorId]": { "siteId": string; "projectorId": string; }
  "/api/admin/field-workers": {}
  "/api/admin/field-workers/[workerId]/work-history": { "workerId": string; }
  "/api/admin/field-workers/create": {}
  "/api/admin/overview": {}
  "/api/admin/projectors": {}
  "/api/admin/services/schedule": {}
  "/api/admin/sites": {}
  "/api/admin/sites/[siteId]": { "siteId": string; }
  "/api/admin/tasks": {}
  "/api/auth/[...all]": { "all": string[]; }
  "/api/blob/upload": {}
  "/api/session": {}
  "/api/user/profile": {}
  "/api/user/services": {}
  "/api/user/services/complete": {}
  "/api/user/services/completed": {}
  "/dashboard": {}
  "/form": {}
  "/login": {}
  "/user/profile": {}
  "/user/services": {}
  "/user/workflow": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
